on: [push]

jobs:
  cognition-deploy:
    runs-on: ubuntu-latest
    name: Deploy experiment to Cognition
    steps:
      - uses: actions/checkout@v3
      - uses: javidalpe/cognition-deploy-action@0.0.0
        with:
          personal-access-token: ${{secrets.PERSONAL_ACCESS_TOKEN}}
          jspsych-version: 6.3.0
      - run: echo "The public link to the task is ${{ steps.deploy.outputs.link }}"