on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Deploy experiment to Cognition
    steps:
      - name: Cognition.run deploy action
        id: deploy
        uses: javidalpe/cognition-run-deploy-action@v1.2.2
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The public link to the task is ${{ steps.deploy.outputs.link }}"